In [4]:
import csv
with open('dataset_GIS/Demographics_US_by_State_Income_Median_Family_Income_(Both_Sexes_-_2017_to_2021)_2017_-_2021.csv', 'r') as f:
    dado = list(csv.reader(f))
    print(dado)

<_csv.reader object at 0x7f90bcfe8c80>

In [118]:
dados = []

In [119]:
import os
import csv
import pandas as pd

dados = []

for idx, filename in enumerate(os.listdir('dataset_GIS/')):
    try:
            if filename.split('.')[-1] == 'csv':
                with open(f'dataset_GIS/{filename}','r') as f:
                    dado = pd.read_csv(f)
                    dados.append(dado)
    except:
        pass

In [125]:
dados[8].columns

Index(['Mortality', ' US by State', ' All Races',
       ' Small Intestine (Both Sexes)', ' 2016 - 2020'],
      dtype='object')

In [123]:
merged_df = dados[0]





for idx,df in enumerate(dados[1:]):
    if idx+1 in [8]:
        #print(df)
        dictionary = {}
        atributos = df.columns
        for i in atributos:
            if i != ' US by State':
                dictionary[i] = f'{i}_{idx}'
            else:
                dictionary[i] = i
        #dictionary[' US by State'] = ' US by State'
        print(df)
        #df = df.rename(dictionary, axis=1)
        #print(df.columns)
        #print(df)
        #merged_df = pd.merge(merged_df, df, on=" US by State")
        #print(merged_df.shape, idx+1)

                                                 Mortality  US by State  \
Area                 State FIPS  Age-Adjusted Rate per 100          000
South Dakota         46                               0.72         0.51
Maine                23                               0.61         0.46
Delaware             10                               0.56         0.40
Oregon               41                               0.56         0.48
District of Columbia 11                               0.55         0.33
Washington           53                               0.55         0.48
Wisconsin            55                               0.53         0.46
Iowa                 19                               0.52         0.43
Virginia             51                               0.50         0.44
Maryland             24                               0.50         0.43
North Carolina       37                               0.49         0.43
Idaho                16                               0.49         0.36
Ohio                 39                               0.49         0.44
South Carolina       45                               0.49         0.42
Kansas               20                               0.47         0.37
Arkansas             5                                0.46         0.36
Indiana              18                               0.46         0.39
Tennessee            47                               0.45         0.39
Pennsylvania         42                               0.45         0.41
Michigan             26                               0.45         0.39
Alaska               2                                0.45         0.25
Vermont              50                               0.43         0.25
Connecticut          9                                0.43         0.35
Illinois             17                               0.43         0.39
Oklahoma             40                               0.43         0.35
Texas                48                               0.42         0.39
Utah                 49                               0.41         0.30
California           6                                0.41         0.39
New York             36                               0.41         0.37
Louisiana            22                               0.40         0.33
Massachusetts        25                               0.40         0.35
Missouri             29                               0.40         0.34
New Jersey           34                               0.39         0.34
Georgia              13                               0.39         0.34
Nebraska             31                               0.38         0.27
Kentucky             21                               0.38         0.30
New Hampshire        33                               0.38         0.26
Florida              12                               0.38         0.35
Minnesota            27                               0.38         0.32
Mississippi          28                               0.37         0.29
North Dakota         38                               0.37         0.22
Alabama              1                                0.36         0.30
Nevada               32                               0.34         0.26
Arizona              4                                0.34         0.29
Colorado             8                                0.33         0.27
Hawaii               15                               0.32         0.22
Montana              30                               0.28         0.16
Rhode Island         44                               0.26         0.15
New Mexico           35                               0.26         0.18
West Virginia        54                               0.24         0.16
Wyoming              56                 no data/suppressed    undefined
undefined            NaN                               NaN          NaN

                                 All Races  Small Intestine (Both Sexes)  \
Area                 State FIPS   Lower CI                      Upper CI
South Dakota         46               1.00                            40
Maine                23               0.80                            61
Delaware             10               0.78                            40
Oregon               41               0.67                           151
District of Columbia 11               0.87                            19
Washington           53               0.63                           242
Wisconsin            55               0.61                           198
Iowa                 19               0.64                           107
Virginia             51               0.56                           249
Maryland             24               0.58                           180
North Carolina       37               0.54                           306
Idaho                16               0.64                            52
Ohio                 39               0.54                           373
South Carolina       45               0.58                           163
Kansas               20               0.59                            82
Arkansas             5                0.57                            83
Indiana              18               0.53                           186
Tennessee            47               0.52                           188
Pennsylvania         42               0.50                           402
Michigan             26               0.50                           287
Alaska               2                0.75                            16
Vermont              50               0.70                            19
Connecticut          9                0.53                           101
Illinois             17               0.48                           332
Oklahoma             40               0.52                           101
Texas                48               0.46                           598
Utah                 49               0.53                            53
California           6                0.44                           906
New York             36               0.44                           500
Louisiana            22               0.49                           109
Massachusetts        25               0.47                           181
Missouri             29               0.47                           160
New Jersey           34               0.45                           226
Georgia              13               0.44                           215
Nebraska             31               0.52                            43
Kentucky             21               0.46                           102
New Hampshire        33               0.55                            35
Florida              12               0.42                           606
Minnesota            27               0.46                           134
Mississippi          28               0.48                            69
North Dakota         38               0.60                            19
Alabama              1                0.44                           108
Nevada               32               0.44                            60
Arizona              4                0.40                           158
Colorado             8                0.40                           102
Hawaii               15               0.46                            31
Montana              30               0.44                            19
Rhode Island         44               0.43                            18
New Mexico           35               0.37                            36
West Virginia        54               0.34                            31
Wyoming              56          undefined                     undefined
undefined            NaN               NaN                           NaN

                                 2016 - 2020
Area                 State FIPS        Count
South Dakota         46                  NaN
Maine                23                  NaN
Delaware             10                  NaN
Oregon               41                  NaN
District of Columbia 11                  NaN
Washington           53                  NaN
Wisconsin            55                  NaN
Iowa                 19                  NaN
Virginia             51                  NaN
Maryland             24                  NaN
North Carolina       37                  NaN
Idaho                16                  NaN
Ohio                 39                  NaN
South Carolina       45                  NaN
Kansas               20                  NaN
Arkansas             5                   NaN
Indiana              18                  NaN
Tennessee            47                  NaN
Pennsylvania         42                  NaN
Michigan             26                  NaN
Alaska               2                   NaN
Vermont              50                  NaN
Connecticut          9                   NaN
Illinois             17                  NaN
Oklahoma             40                  NaN
Texas                48                  NaN
Utah                 49                  NaN
California           6                   NaN
New York             36                  NaN
Louisiana            22                  NaN
Massachusetts        25                  NaN
Missouri             29                  NaN
New Jersey           34                  NaN
Georgia              13                  NaN
Nebraska             31                  NaN
Kentucky             21                  NaN
New Hampshire        33                  NaN
Florida              12                  NaN
Minnesota            27                  NaN
Mississippi          28                  NaN
North Dakota         38                  NaN
Alabama              1                   NaN
Nevada               32                  NaN
Arizona              4                   NaN
Colorado             8                   NaN
Hawaii               15                  NaN
Montana              30                  NaN
Rhode Island         44                  NaN
New Mexico           35                  NaN
West Virginia        54                  NaN
Wyoming              56                  NaN
undefined            NaN                 NaN

In [55]:
os.listdir('dataset_GIS/')[8]

'Mortality_US_by_State_All_Races_Small_Intestine_(Both_Sexes)_2016_-_2020 (1).csv'

In [88]:
dados[8]

,,Mortality,US by State,All Races,Small Intestine (Both Sexes),2016 - 2020
Area,State FIPS,Age-Adjusted Rate per 100,000,Lower CI,Upper CI,Count
South Dakota,46,0.72,0.51,1.00,40,NaN
Maine,23,0.61,0.46,0.80,61,NaN
Delaware,10,0.56,0.40,0.78,40,NaN
Oregon,41,0.56,0.48,0.67,151,NaN
District of Columbia,11,0.55,0.33,0.87,19,NaN
Washington,53,0.55,0.48,0.63,242,NaN
Wisconsin,55,0.53,0.46,0.61,198,NaN
Iowa,19,0.52,0.43,0.64,107,NaN
Virginia,51,0.50,0.44,0.56,249,NaN
Maryland,24,0.50,0.43,0.58,180,NaN
North Carolina,37,0.49,0.43,0.54,306,NaN
Idaho,16,0.49,0.36,0.64,52,NaN
Ohio,39,0.49,0.44,0.54,373,NaN
South Carolina,45,0.49,0.42,0.58,163,NaN
Kansas,20,0.47,0.37,0.59,82,NaN
Arkansas,5,0.46,0.36,0.57,83,NaN
Indiana,18,0.46,0.39,0.53,186,NaN
Tennessee,47,0.45,0.39,0.52,188,NaN
Pennsylvania,42,0.45,0.41,0.50,402,NaN
Michigan,26,0.45,0.39,0.50,287,NaN
Alaska,2,0.45,0.25,0.75,16,NaN
Vermont,50,0.43,0.25,0.70,19,NaN
Connecticut,9,0.43,0.35,0.53,101,NaN
Illinois,17,0.43,0.39,0.48,332,NaN
Oklahoma,40,0.43,0.35,0.52,101,NaN
Texas,48,0.42,0.39,0.46,598,NaN
Utah,49,0.41,0.30,0.53,53,NaN
California,6,0.41,0.39,0.44,906,NaN
New York,36,0.41,0.37,0.44,500,NaN
Louisiana,22,0.40,0.33,0.49,109,NaN
Massachusetts,25,0.40,0.35,0.47,181,NaN
Missouri,29,0.40,0.34,0.47,160,NaN
New Jersey,34,0.39,0.34,0.45,226,NaN
Georgia,13,0.39,0.34,0.44,215,NaN
Nebraska,31,0.38,0.27,0.52,43,NaN
Kentucky,21,0.38,0.30,0.46,102,NaN
New Hampshire,33,0.38,0.26,0.55,35,NaN
Florida,12,0.38,0.35,0.42,606,NaN
Minnesota,27,0.38,0.32,0.46,134,NaN
Mississippi,28,0.37,0.29,0.48,69,NaN
North Dakota,38,0.37,0.22,0.60,19,NaN
Alabama,1,0.36,0.30,0.44,108,NaN
Nevada,32,0.34,0.26,0.44,60,NaN
Arizona,4,0.34,0.29,0.40,158,NaN
Colorado,8,0.33,0.27,0.40,102,NaN
Hawaii,15,0.32,0.22,0.46,31,NaN
Montana,30,0.28,0.16,0.44,19,NaN
Rhode Island,44,0.26,0.15,0.43,18,NaN
New Mexico,35,0.26,0.18,0.37,36,NaN
West Virginia,54,0.24,0.16,0.34,31,NaN
Wyoming,56,no data/suppressed,undefined,undefined,undefined,NaN
undefined,NaN,NaN,NaN,NaN,NaN,NaN